### ISSUE TITLE
Multi chats en el bot

### ISSUE THREAD

**Issue by escalonc** [unitec-repositorios/VinculacionUnitec-SPS#1]
Hacer que el bot sea capaz de aguantar colisiones y responda correctamente a los diferentes usuarios haciendo las consultas al mismo tiempo 
- Investigar como permitir al bot multi chats
- manejar el estado de cada chat (Identificando cada chat de forma unica ejm: chatID, Numero de cuenta, Usuario de telegram y el ultimo mensaje enviado)
- Respuesta asincrona (prioridad)

**Comment by GeraHn10** [comment]
Bot capaz de responder multisesiones

**Comment by GeraHn10** [comment]
El Bot es capaz de responder a varios usuarios con la información correcta
